name = "pm-dashboard"
compatibility_date = "2024-08-15"

[vars]
OPENAI_MODEL = "gpt-4o-mini"

[[d1_databases]]
binding = "DB"
database_name = "contentdb"
database_id = "d4ebd9b4-686d-4dc8-8588-984e2d6095d0"
